apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- realtime.yaml
- redis.yaml

vars:
- name: REDISSERVICE
  objref:
    kind: Service
    name: redis
    apiVersion: v1
- name: REDISNAMESPACE
  objref:
    kind: Service
    name: redis
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace



    #export GITHUB_TOKEN="xxxx-xxxx"
    # #export GITHUB_USER=Pacifique2
    # flux bootstrap github \
    # --owner=$GITHUB_USER \
    # --repository=flux-infra \
    # --branch=main \
    # --path=app-cluster \
    # --personal

    # flux create source git go-app-kustomize-infra --url=https://github.com/Pacifique2/go-app-kustomize-infra \
    # --branch=master \
    # --interval=30s \
    # --export > ./app-cluster/realtimeapp-source.yaml
    # #dev
    # flux create kustomization realtimeapp-dev \
    # --source=go-app-kustomize-infra \
    # --path="./deploy/overlays/dev" \
    # --prune=true \
    # --interval=1m \
    # --validation=client \
    # --health-check="Deployment/realtime-dev.realtime-dev" \
    # --health-check="Deployment/redis-dev.realtime-dev" \
    # --health-check-timeout=2m \
    # --export > ./app-cluster/realtimeapp-dev.yaml
    # #prd
    # flux create kustomization realtimeapp-prd \
    # --source=go-app-kustomize-infra \
    # --path="./deploy/overlays/prd" \
    # --prune=true \
    # --interval=1m \
    # --validation=client \
    # --health-check="Deployment/realtime-prd.realtime-prd" \
    # --health-check="Deployment/redis-prd.realtime-prd" \
    # --health-check-timeout=2m \
    # --export > ./app-cluster/realtimeapp-prd.yaml

    # flux create helmrelease redis \
    # --source=HelmRepository/bitnami \
    # --chart redis \
    # --release-name redis \
    # --target-namespace default \
    # --internal 5m0s \

    # --export > helmrelease-redis.yaml

    # az keyvault secret show \
    #    --name PATDEVOPS \
    #            --vault-name azkvpxcmp01

    

    
